# Generated by Django 3.2.21 on 2023-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('unix_like', models.CharField(max_length=20)),
                ('owner_id', models.IntegerField()),
            ],
        ),
    ]
