# Generated by Django 3.2.21 on 2023-12-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IP', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Owner',
        ),
    ]
