# Generated by Django 3.2.21 on 2023-12-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IP', '0003_rename_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='unix_like',
            field=models.BooleanField(),
        ),
    ]
