# Generated by Django 4.2.7 on 2024-01-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IP', '0004_alter_ip_unix_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IP.owner'),
        ),
    ]
