# Generated by Django 4.2.7 on 2024-01-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IP', '0005_alter_ip_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
